---
- name: install maven and jdk
  hosts: db
  become: yes

  tasks:  
    - name:  Ensure maven service is present
      apt:
        name: maven
        state: present

    - name:  Ensure default-jdk service is present
      apt:
        name: default-jdk
        state: present

    - name:  Ensure git service is present
      apt:
        name: git
        state: present

    - name: Creates directory /boxfuse
      file:
        path: /boxfuse
        state: directory
        mode: '0755'
        recurse: yes

    - name: Clone repository boxfuse
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello  
        dest: /boxfuse/boxfuse-sample-java-war-hello
        force: true

    - name: Build maven
      shell: mvn package
      args:
        chdir: /boxfuse/boxfuse-sample-java-war-hello
    

- name: install tomcat9
  hosts: web
  become: yes
  
  tasks:
    - name: Ensure tomcat package is present
      apt:
        name: tomcat9
        state: present

    - name: Ensure tomcat service is started
      service:
        name: tomcat9
        state: started
    
    - name: Transfer file hello-1.0.war from db(212.233.90.249) to web(212.233.91.51)
      remote_user: root
      synchronize:
        src: /boxfuse/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/hello-1.0.war
      delegate_to: 212.233.90.249
