FROM maven:3.9.4-eclipse-temurin-11-focal

RUN apt-get update && apt-get install -y apt-transport-https gnupg2 software-properties-common

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    apt-get -y install docker-ce
    
RUN apt-get clean